language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

before_install: 
  - docker build -t tkthuc/docker-react -f Dockerfile.dev .

script:
  - docker run tkthuc/docker-react npm run test -- --coverage


